from __future__ import annotations

from app.config import settings

try:
    from crewai import Agent, Crew, Task
    from crewai.llm import LLM
    from crewai_tools import DirectoryReadTool, FileReadTool
except ImportError:  # pragma: no cover
    Agent = Crew = Task = LLM = DirectoryReadTool = FileReadTool = None


class PaperAnalysisService:
    def __init__(self) -> None:
        self.api_key = settings.openai_api_key.strip()
        self.model = settings.openai_model

    def analyze(self, title: str, abstract: str, conclusion: str) -> dict[str, str]:
        if self._can_use_crewai():
            try:
                return self._analyze_with_crewai(title=title, abstract=abstract, conclusion=conclusion)
            except Exception as exc:  # pragma: no cover
                fallback = self._fallback_analysis(abstract=abstract, conclusion=conclusion)
                fallback["methodology"] = "\n".join(
                    [
                        "- CrewAI execution failed, so fallback output is being shown instead.",
                        f"- Error summary: {exc}",
                        fallback["methodology"],
                    ]
                )
                return fallback
        return self._fallback_analysis(abstract=abstract, conclusion=conclusion)

    def _can_use_crewai(self) -> bool:
        return bool(self.api_key and Agent and Crew and Task and LLM and DirectoryReadTool and FileReadTool)

    def _analyze_with_crewai(self, title: str, abstract: str, conclusion: str) -> dict[str, str]:
        from app.crew.crew_builder import run_paper_analysis_crew

        return run_paper_analysis_crew(title=title, abstract=abstract, conclusion=conclusion)

    def _fallback_analysis(self, abstract: str, conclusion: str) -> dict[str, str]:
        joined_text = f"{abstract}\n\n{conclusion}".strip()
        sentences = [sentence.strip() for sentence in joined_text.replace("\n", " ").split(".") if sentence.strip()]

        methodology_points = [
            "Method could not be generated by CrewAI because the OpenAI API key or CrewAI package is unavailable.",
            f"Abstract length: {len(abstract.split())} words.",
            "Look for phrases describing experiments, datasets, models, surveys, interviews, or case studies in the abstract.",
        ]
        findings_points = [
            sentences[0] if sentences else "No findings could be inferred from the provided text.",
            sentences[-1] if len(sentences) > 1 else "Add an OpenAI API key to generate stronger finding summaries.",
        ]
        gap_points = [
            "Research gaps could not be fully inferred without live model analysis.",
            "Check the conclusion for phrases like limitation, future work, remains unclear, or can be extended.",
            "Use this fallback output as a placeholder until CrewAI is configured.",
        ]

        return {
            "methodology": self._to_bullets(methodology_points),
            "findings": self._to_bullets(findings_points),
            "research_gaps": self._to_bullets(gap_points),
        }

    @staticmethod
    def _to_bullets(items: list[str]) -> str:
        return "\n".join(f"- {item}" for item in items)
